export const GALLERY_IMAGES = [
  {
    id: 1,
    src: "/images/tattoo1.jpg",
    alt: "Traditional dragon tattoo",
    category: "Traditional",
    artist: "Mike Rodriguez",
  },
  {
    id: 2,
    src: "/images/tattoo2.jpg",
    alt: "Realistic portrait tattoo",
    category: "Realism",
    artist: "Sarah Chen",
  },
  {
    id: 3,
    src: "/images/tattoo3.jpg",
    alt: "Geometric mandala tattoo",
    category: "Geometric",
    artist: "Alex Johnson",
  },
  {
    id: 4,
    src: "/images/tattoo4.jpg",
    alt: "Watercolor flower tattoo",
    category: "Watercolor",
    artist: "Emma Davis",
  },
  {
    id: 5,
    src: "/images/tattoo5.jpg",
    alt: "Blackwork sleeve tattoo",
    category: "Blackwork",
    artist: "Chris Wilson",
  },
  {
    id: 6,
    src: "/images/tattoo6.jpg",
    alt: "Neo-traditional tattoo",
    category: "Neo-Traditional",
    artist: "Jordan Lee",
  },
  {
    id: 7,
    src: "/images/tattoo7.jpg",
    alt: "Japanese style tattoo",
    category: "Japanese",
    artist: "Yuki Tanaka",
  },
  {
    id: 8,
    src: "/images/tattoo8.jpg",
    alt: "Minimalist line tattoo",
    category: "Minimalist",
    artist: "Taylor Swift",
  },
  {
    id: 9,
    src: "/images/tattoo9.jpg",
    alt: "Surreal art tattoo",
    category: "Surreal",
    artist: "Riley Parker",
  },
] as const;

export const ARTISTS = [
  {
    id: 1,
    name: "Mike Rodriguez",
    specialty: "Traditional & Neo-Traditional",
    experience: "12+ years",
    bio: "Master of bold lines and vibrant colors with a passion for traditional American tattooing.",
    image: "/images/artist1.jpg",
    instagram: "@mike_ink_rebellion",
  },
  {
    id: 2,
    name: "Sarah Chen",
    specialty: "Realism & Portraits",
    experience: "8+ years",
    bio: "Specializes in photorealistic portraits and intricate detail work.",
    image: "/images/artist2.jpg",
    instagram: "@sarah_realistic_ink",
  },
  {
    id: 3,
    name: "Alex Johnson",
    specialty: "Geometric & Sacred Geometry",
    experience: "6+ years",
    bio: "Creates stunning geometric patterns and sacred geometry designs.",
    image: "/images/artist3.jpg",
    instagram: "@alex_geometric_art",
  },
] as const;
